version: '3.3'

services:
   db:
     image: mysql:5.7
     ports: 
        - 127.0.0.1:3306:3306
     command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
        ]
     expose:
        - '3306'
     environment:
        MYSQL_DATABASE: wp
        MYSQL_ROOT_PASSWORD: password
        MYSQL_ROOT_HOST: '%'
     networks:
        - wordpress-network

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - 127.0.0.1:80:80
     volumes:
       - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
       - /Users/macbookproritena/Documents/web/bvb:/var/www/html
       - ./wp-theme-bvb/:/var/www/html/wp/wp-content/themes/wp-theme-bvb
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_NAME: wp
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: password
     networks:
       - wordpress-network
networks:
   wordpress-network:
     driver: bridge
